influxdb:
  image: influxdb:latest
  container_name: influxdb
  ports:
    - "8083:8083"
    - "8086:8086"
    - "8090:8090"
  environment:
    - INFLUXDB_DB=puppeteer
    - INFLUXDB_ADMIN_USER=root
    - INFLUXDB_ADMIN_PASSWORD=root
  volumes:
    - ./provisioning.yml:/etc/grafana/provisioning

grafana:
  image: grafana/grafana:latest
  container_name: grafana
  ports:
    - "3000:3000"
  user: "0"
  links:
    - influxdb